version: 2.1

jobs:
  test:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run: 
          name: Run test
          command: |
            npm run test
  lint:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Lint project
          command: |
            npm run lint
  
  analyze:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Analyze project dependencies
          command: |
            npm audit

  build_docker_image:
    docker:
      - image: docker:stable
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build docker image
            command: |
              docker build --tag sort-ms .
  

workflows:
  ci:
    jobs:
      - test
      - lint
      - analyze
      - build_docker_image:
          requires: [test, lint, analyze]