version: 2.1

executors:
  node:
    docker:
      - image: node:16-alpine

  docker-publisher:
    environment:
      IMAGE_TAG: ddanny99/sort-ms:latest
    docker:
      - image: docker:stable

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run: 
          name: Run test
          command: |
            npm run test
  lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Lint project
          command: |
            npm run lint
  
  analyze:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Analyze project dependencies
          command: |
            npm audit

  build_docker_image:
    executor: docker-publisher
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build docker image
            command: |
              docker build --tag "${IMAGE_TAG}" .
        - run:
            name: Save Docker image
            command: |
              docker save --ouput image.tar "${IMAGE_TAG}"
        - persist_to_workspace:
            root: .
            paths:
              - ./image.tar
  
  # pusb_docker_image:
  #     executor: docker-publisher
  #     steps:
  #       - checkout
  #       - setup_remote_docker


workflows:
  ci:
    jobs:
      - test
      - lint
      - analyze
      - build_docker_image:
          requires: [test, lint, analyze]